---

name: 'Test Docker-Image'

on: [push]

jobs:
  test-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: make test

...
